### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by Ijazweb** [omarKazoum/php-http-router#1]
hi, i want to know how to accept  non english word in url 
accept any language and - separator  in url.

**Comment by omarKazoum** [comment]
hi @Ijazweb  glad that your are interested in this subject ! 
please give us a sample of the words you want to include in the url.

**Comment by Ijazweb** [comment]
localhost/post/ما-فائدته/
localhost/post/क्या-है/
means accept all language with ( - ) separator.
Router::get('post/{slug}',[new PostController,'view']);

**Comment by omarKazoum** [comment]
enjoy @Ijazweb !
